-- ============================================================================
-- Backend de Aplicaciones - DDL H2 (estructura inicial)
-- Nota: H2 convierte identificadores NO entrecomillados a MAYÚSCULAS.
--       Mantenemos el esquema MAIN para reflejar el "main." de SQLite.
-- ============================================================================

-- Limpieza opcional (si se re-ejecuta el script)
DROP TABLE IF EXISTS JUEGOS;
DROP TABLE IF EXISTS PLATAFORMAS;
DROP TABLE IF EXISTS DESARROLLADORES;
DROP TABLE IF EXISTS GENEROS;

DROP SEQUENCE IF EXISTS SEQ_JUEGOS;
DROP SEQUENCE IF EXISTS SEQ_PLATAFORMAS;
DROP SEQUENCE IF EXISTS SEQ_DESARROLLADORES;
DROP SEQUENCE IF EXISTS SEQ_GENEROS;

-- Secuencias (todas comienzan en 1)
CREATE SEQUENCE SEQ_DESARROLLADORES START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_GENEROS          START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_PLATAFORMAS      START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_JUEGOS           START WITH 1 INCREMENT BY 1;

-- DESARROLLADORES
CREATE TABLE DESARROLLADORES
(
    DESA_ID     INT NOT NULL DEFAULT NEXT VALUE FOR SEQ_DESARROLLADORES,
    NOMBRE      VARCHAR(255) NOT NULL,
    CONSTRAINT PK_DESARROLLADORES PRIMARY KEY  (DESA_ID)
);

-- GENEROS
CREATE TABLE GENEROS (
     GEN_ID       INT NOT NULL DEFAULT NEXT VALUE FOR SEQ_GENEROS,
     NOMBRE       VARCHAR(255) NOT NULL,
     CONSTRAINT PK_GENEROS PRIMARY KEY (GEN_ID)
);

-- PLATAFORMAS
CREATE TABLE PLATAFORMAS (
    PLAT_ID      INT NOT NULL DEFAULT NEXT VALUE FOR SEQ_PLATAFORMAS,
    NOMBRE       VARCHAR(255) NOT NULL,
    CONSTRAINT PK_PLATAFORMAS PRIMARY KEY (PLAT_ID)
);

-- JUEGOS
CREATE TABLE JUEGOS (
    JUEGO_ID                INT NOT NULL DEFAULT NEXT VALUE FOR SEQ_JUEGOS,
    TITULO                  VARCHAR(255) NOT NULL,
    FECHA_LANZAMIENTO       INTEGER,
    GENERO_ID               INTEGER,
    DESARROLLADOR_ID        INTEGER,
    CLASIFICACION_ESRB   VARCHAR(4),
    PLATAFORMA_ID           INTEGER,
    RATING                  DOUBLE,
    JUEGOS_FINALIZADOS      INTEGER,
    JUGANDO                 INTEGER,
    RESUMEN                 CLOB NOT NULL,

    CONSTRAINT PK_JUEGOS PRIMARY KEY (JUEGO_ID),
    CONSTRAINT FK_JUEGOS_GENEROS
        FOREIGN KEY (GENERO_ID) REFERENCES GENEROS(GEN_ID),
    CONSTRAINT FK_JUEGOS_DESARROLLADORES
        FOREIGN KEY (DESARROLLADOR_ID) REFERENCES DESARROLLADORES(DESA_ID),
    CONSTRAINT FK_JUEGOS_PLATAFORMAS
        FOREIGN KEY (PLATAFORMA_ID) REFERENCES PLATAFORMAS(PLAT_ID)
);

-- Índices sugeridos (optativos) para mejorar joins/búsquedas por FK
CREATE INDEX IF NOT EXISTS IX_JUEGOS_GENERO       ON JUEGOS(GENERO_ID);
CREATE INDEX IF NOT EXISTS IX_JUEGOS_DESA         ON JUEGOS(DESARROLLADOR_ID);
CREATE INDEX IF NOT EXISTS IX_JUEGOS_PLATAFORMA   ON JUEGOS(PLATAFORMA_ID);
